

// This file should be generated by the FlutterFire CLI.
// Ensure you have run `flutterfire configure` to generate this file.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static const currentPlatform = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
  );
}